<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Rp0_signin-iframe</name>
   <tag></tag>
   <elementGuidId>ec3ff5c6-fe2f-4cb2-a847-49f795b3b8e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.signin-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signin-iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ap/signin?openid.ns=http://specs.openid.net/auth/2.0&amp;openid.assoc_handle=amzn_bookdepository_website_uk&amp;openid.mode=checkid_setup&amp;openid.return_to=https://www.bookdepository.com/It-Ends-With-Us-most-heartbreaking-novel-youll-ever-read-Colleen-Hoover/9781471156267?ref%3Dgrid-view%26status%3Dwelcome&amp;openid.pape.max_auth_age=0&amp;openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&amp;pageId=bookdepo_website_embed&amp;rmrMeDefaultSelected=1&amp;language=en_US</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>csmWidgetEnd('signin-iframe-load');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-touchevents flexbox csscolumns csscolumns-width csscolumns-span csscolumns-fill csscolumns-gap csscolumns-rule csscolumns-rulecolor csscolumns-rulestyle csscolumns-rulewidth csscolumns-breakbefore csscolumns-breakafter csscolumns-breakinside smil&quot;]/body[@class=&quot;js&quot;]/div[@class=&quot;page-slide&quot;]/div[@class=&quot;content-wrap&quot;]/div[@class=&quot;main-content full-width no-borders login-page&quot;]/div[@class=&quot;block-wrap half&quot;]/div[@class=&quot;signin-iframe-wrapper&quot;]/div[@class=&quot;loading-animation background-image-hidden&quot;]/iframe[@class=&quot;signin-iframe&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/iframe</value>
   </webElementXpaths>
</WebElementEntity>
